### ISSUE TITLE
DO58 As an organisational admin, I want to make outputs easily accessible, usable, simple and user friendly so that I can use my time effectively within the MNR. 

### ISSUE THREAD

**Issue by TetrienneBox** [jncc/marine-noise-registry#219]

**Comment by TetrienneBox** [comment]
this was to reflect the concerns that the organisational admin role, may add burden. so whatever was created for the organisational admin, was user friendly. the group felt this was important to capture.

**Comment by LynnHeeley** [comment]
This is an objective rather than a specific users story that can be built (hence rejected as a user story and closed). Creating outputs relates to the user support role rather than org admin role.
